
# Configuração das funções edge do Supabase
[functions]
[functions.learnworlds-courses-sync]
verify_jwt = false

[functions.learnworlds-sync]
verify_jwt = false

[functions.learnworlds-api]
verify_jwt = false

[functions.create-profile]
verify_jwt = false

[functions.send-auth-email]
verify_jwt = false

[functions.send-confirmation-email]
verify_jwt = false
