
project_id = "bioarzkfmcobctblzztm"

[functions.send-payment-email]
verify_jwt = true

[functions.learnworlds-api]
verify_jwt = true

[functions.asaas-payments]
verify_jwt = true

[functions.lytex-integration]
verify_jwt = true
