
project_id = "bioarzkfmcobctblzztm"

[api]
enabled = true
port = 8000
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 5432
shadow_port = 5433
major_version = 15

[studio]
enabled = true
port = 3000
api_url = "http://localhost"

[inbucket]
enabled = true
port = 4000

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://localhost:3000"

[analytics]
enabled = false
port = 9000
vector_port = 8000

# FUNCTIONS
[functions.learnworlds-api]
verify_jwt = true

[functions.learnworlds-sync]
verify_jwt = true

[functions.create-profile]
verify_jwt = true

[functions.learnworlds-courses-sync]
verify_jwt = true
