import React, { useState, useEffect } from "react";
import { useParams } from "react-router-dom";
import MainLayout from "@/components/layout/MainLayout";
import { Card, CardContent, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Link } from "react-router-dom";
import { Clock, Award, Search } from "lucide-react";
import { Input } from "@/components/ui/input";

// Dados simulados para os cursos
const mockCourses = [
  // Cursos existentes
  {
    id: 1,
    title: "Administração de Empresas",
    category: "Graduação",
    categorySlug: "graduacao",
    duration: "4 anos",
    price: "R$ 597,00",
    originalPrice: "R$ 897,00",
    image: "/placeholder.svg",
  },
  {
    id: 2,
    title: "Pedagogia",
    category: "Graduação",
    categorySlug: "graduacao",
    duration: "4 anos",
    price: "R$ 547,00",
    originalPrice: "R$ 847,00",
    image: "/placeholder.svg",
  },
  {
    id: 3,
    title: "Engenharia Civil",
    category: "Segunda Graduação",
    categorySlug: "segunda-graduacao",
    duration: "3 anos",
    price: "R$ 697,00",
    originalPrice: "R$ 997,00",
    image: "/placeholder.svg",
  },
  {
    id: 4,
    title: "Gestão de Recursos Humanos",
    category: "Pós-Graduação",
    categorySlug: "pos-graduacao",
    duration: "1.5 anos",
    price: "R$ 397,00",
    originalPrice: "R$ 597,00",
    image: "/placeholder.svg",
  },
  {
    id: 5,
    title: "Marketing Digital",
    category: "Pós-Graduação",
    categorySlug: "pos-graduacao",
    duration: "1.5 anos",
    price: "R$ 427,00",
    originalPrice: "R$ 627,00",
    image: "/placeholder.svg",
  },
  {
    id: 6,
    title: "Excel Avançado",
    category: "Formação Livre",
    categorySlug: "formacao-livre",
    duration: "60 horas",
    price: "R$ 197,00",
    originalPrice: "R$ 297,00",
    image: "/placeholder.svg",
  },
  {
    id: 7,
    title: "Técnicas de Vendas",
    category: "Capacitação Profissional",
    categorySlug: "capacitacao-profissional",
    duration: "80 horas",
    price: "R$ 247,00",
    originalPrice: "R$ 347,00",
    image: "/placeholder.svg",
  },
  {
    id: 8,
    title: "Data Science",
    category: "Capacitação Profissional",
    categorySlug: "capacitacao-profissional",
    duration: "120 horas",
    price: "R$ 347,00",
    originalPrice: "R$ 447,00",
    image: "/placeholder.svg",
  },
  
  // Novos cursos de graduação tecnológica (18 meses)
  {
    id: 9,
    title: "Análise e Desenvolvimento de Sistemas",
    category: "Graduação Tecnológica",
    categorySlug: "graduacao",
    duration: "18 meses",
    price: "R$ 497,00",
    originalPrice: "R$ 697,00",
    image: "/placeholder.svg",
  },
  {
    id: 10,
    title: "Big Data e Inteligência Analítica",
    category: "Graduação Tecnológica",
    categorySlug: "graduacao",
    duration: "18 meses",
    price: "R$ 497,00",
    originalPrice: "R$ 697,00",
    image: "/placeholder.svg",
  },
  {
    id: 11,
    title: "Cidades Inteligentes",
    category: "Graduação Tecnológica",
    categorySlug: "graduacao",
    duration: "18 meses",
    price: "R$ 497,00",
    originalPrice: "R$ 697,00",
    image: "/placeholder.svg",
  },
  {
    id: 12,
    title: "Coaching e Desenvolvimento Humano",
    category: "Graduação Tecnológica",
    categorySlug: "graduacao",
    duration: "18 meses",
    price: "R$ 497,00",
    originalPrice: "R$ 697,00",
    image: "/placeholder.svg",
  },
  {
    id: 13,
    title: "Comércio Exterior",
    category: "Graduação Tecnológica",
    categorySlug: "graduacao",
    duration: "18 meses",
    price: "R$ 497,00",
    originalPrice: "R$ 697,00",
    image: "/placeholder.svg",
  },
  {
    id: 14,
    title: "Design de Animação",
    category: "Graduação Tecnológica",
    categorySlug: "graduacao",
    duration: "18 meses",
    price: "R$ 497,00",
    originalPrice: "R$ 697,00",
    image: "/placeholder.svg",
  },
  {
    id: 15,
    title: "Designer de Interiores",
    category: "Graduação Tecnológica",
    categorySlug: "graduacao",
    duration: "18 meses",
    price: "R$ 497,00",
    originalPrice: "R$ 697,00",
    image: "/placeholder.svg",
  },
  {
    id: 16,
    title: "Designer de Produto",
    category: "Graduação Tecnológica",
    categorySlug: "graduacao",
    duration: "18 meses",
    price: "R$ 497,00",
    originalPrice: "R$ 697,00",
    image: "/placeholder.svg",
  },
  {
    id: 17,
    title: "Designer Gráfico",
    category: "Graduação Tecnológica",
    categorySlug: "graduacao",
    duration: "18 meses",
    price: "R$ 497,00",
    originalPrice: "R$ 697,00",
    image: "/placeholder.svg",
  },
  {
    id: 18,
    title: "Despachante Documentalista",
    category: "Graduação Tecnológica",
    categorySlug: "graduacao",
    duration: "18 meses",
    price: "R$ 497,00",
    originalPrice: "R$ 697,00",
    image: "/placeholder.svg",
  },
  {
    id: 19,
    title: "Educador Social",
    category: "Graduação Tecnológica",
    categorySlug: "graduacao",
    duration: "18 meses",
    price: "R$ 497,00",
    originalPrice: "R$ 697,00",
    image: "/placeholder.svg",
  },
  {
    id: 20,
    title: "Empreendedorismo Educacional",
    category: "Graduação Tecnológica",
    categorySlug: "graduacao",
    duration: "18 meses",
    price: "R$ 497,00",
    originalPrice: "R$ 697,00",
    image: "/placeholder.svg",
  },
  {
    id: 21,
    title: "Estética e Cosmética",
    category: "Graduação Tecnológica",
    categorySlug: "graduacao",
    duration: "18 meses",
    price: "R$ 497,00",
    originalPrice: "R$ 697,00",
    image: "/placeholder.svg",
  },
  {
    id: 22,
    title: "Gestão Ambiental",
    category: "Graduação Tecnológica",
    categorySlug: "graduacao",
    duration: "18 meses",
    price: "R$ 497,00",
    originalPrice: "R$ 697,00",
    image: "/placeholder.svg",
  },
  {
    id: 23,
    title: "Gestão Comercial",
    category: "Graduação Tecnológica",
    categorySlug: "graduacao",
    duration: "18 meses",
    price: "R$ 497,00",
    originalPrice: "R$ 697,00",
    image: "/placeholder.svg",
  },
  {
    id: 24,
    title: "Gestão da Produção Industrial",
    category: "Graduação Tecnológica",
    categorySlug: "graduacao",
    duration: "18 meses",
    price: "R$ 497,00",
    originalPrice: "R$ 697,00",
    image: "/placeholder.svg",
  },
  {
    id: 25,
    title: "Gestão da Qualidade",
    category: "Graduação Tecnológica",
    categorySlug: "graduacao",
    duration: "18 meses",
    price: "R$ 497,00",
    originalPrice: "R$ 697,00",
    image: "/placeholder.svg",
  },
  {
    id: 26,
    title: "Gestão de Agronegócios",
    category: "Graduação Tecnológica",
    categorySlug: "graduacao",
    duration: "18 meses",
    price: "R$ 497,00",
    originalPrice: "R$ 697,00",
    image: "/placeholder.svg",
  },
  {
    id: 27,
    title: "Gestão de Clínica e Consultório",
    category: "Graduação Tecnológica",
    categorySlug: "graduacao",
    duration: "18 meses",
    price: "R$ 497,00",
    originalPrice: "R$ 697,00",
    image: "/placeholder.svg",
  },
  {
    id: 28,
    title: "Gestão de Cooperativas",
    category: "Graduação Tecnológica",
    categorySlug: "graduacao",
    duration: "18 meses",
    price: "R$ 497,00",
    originalPrice: "R$ 697,00",
    image: "/placeholder.svg",
  },
  {
    id: 29,
    title: "Gestão de Investimentos",
    category: "Graduação Tecnológica",
    categorySlug: "graduacao",
    duration: "18 meses",
    price: "R$ 497,00",
    originalPrice: "R$ 697,00",
    image: "/placeholder.svg",
  },
  
  // Novos cursos de licenciatura (3.5+ anos)
  {
    id: 30,
    title: "Artes Visuais",
    category: "Licenciatura",
    categorySlug: "graduacao",
    duration: "3.5 anos",
    price: "R$ 497,00",
    originalPrice: "R$ 697,00",
    image: "/placeholder.svg",
  },
  {
    id: 31,
    title: "Ciências da Religião",
    category: "Licenciatura",
    categorySlug: "graduacao",
    duration: "3.5 anos",
    price: "R$ 497,00",
    originalPrice: "R$ 697,00",
    image: "/placeholder.svg",
  },
  {
    id: 32,
    title: "Educação Especial",
    category: "Licenciatura",
    categorySlug: "graduacao",
    duration: "3.5 anos",
    price: "R$ 497,00",
    originalPrice: "R$ 697,00",
    image: "/placeholder.svg",
  },
  {
    id: 33,
    title: "Educação Física",
    category: "Licenciatura",
    categorySlug: "graduacao",
    duration: "3.5 anos",
    price: "R$ 497,00",
    originalPrice: "R$ 697,00",
    image: "/placeholder.svg",
  },
  {
    id: 34,
    title: "Filosofia",
    category: "Licenciatura",
    categorySlug: "graduacao",
    duration: "3.5 anos",
    price: "R$ 497,00",
    originalPrice: "R$ 697,00",
    image: "/placeholder.svg",
  },
  {
    id: 35,
    title: "Geografia",
    category: "Licenciatura",
    categorySlug: "graduacao",
    duration: "3.5 anos",
    price: "R$ 497,00",
    originalPrice: "R$ 697,00",
    image: "/placeholder.svg",
  },
  {
    id: 36,
    title: "História",
    category: "Licenciatura",
    categorySlug: "graduacao",
    duration: "3.5 anos",
    price: "R$ 497,00",
    originalPrice: "R$ 697,00",
    image: "/placeholder.svg",
  },
  {
    id: 37,
    title: "Letras - Língua Portuguesa e Libras",
    category: "Licenciatura",
    categorySlug: "graduacao",
    duration: "3.5 anos",
    price: "R$ 497,00",
    originalPrice: "R$ 697,00",
    image: "/placeholder.svg",
  },
  {
    id: 38,
    title: "Letras - Português e Espanhol",
    category: "Licenciatura",
    categorySlug: "graduacao",
    duration: "3.5 anos",
    price: "R$ 497,00",
    originalPrice: "R$ 697,00",
    image: "/placeholder.svg",
  },
  {
    id: 39,
    title: "Letras - Português e Inglês",
    category: "Licenciatura",
    categorySlug: "graduacao",
    duration: "3.5 anos",
    price: "R$ 497,00",
    originalPrice: "R$ 697,00",
    image: "/placeholder.svg",
  },
  {
    id: 40,
    title: "Pedagogia",
    category: "Licenciatura",
    categorySlug: "graduacao",
    duration: "3.5 anos",
    price: "R$ 497,00",
    originalPrice: "R$ 697,00",
    image: "/placeholder.svg",
  },
  {
    id: 41,
    title: "Sociologia",
    category: "Licenciatura",
    categorySlug: "graduacao",
    duration: "3.5 anos",
    price: "R$ 497,00",
    originalPrice: "R$ 697,00",
    image: "/placeholder.svg",
  },
  
  // Novos cursos de Bacharelado (3.5+ anos)
  {
    id: 42,
    title: "Administração",
    category: "Bacharelado",
    categorySlug: "graduacao",
    duration: "4 anos",
    price: "R$ 547,00",
    originalPrice: "R$ 747,00",
    image: "/placeholder.svg",
  },
  {
    id: 43,
    title: "Biblioteconomia",
    category: "Bacharelado",
    categorySlug: "graduacao",
    duration: "4 anos",
    price: "R$ 547,00",
    originalPrice: "R$ 747,00",
    image: "/placeholder.svg",
  },
  {
    id: 44,
    title: "Ciências Contábeis",
    category: "Bacharelado",
    categorySlug: "graduacao",
    duration: "4 anos",
    price: "R$ 547,00",
    originalPrice: "R$ 747,00",
    image: "/placeholder.svg",
  },
  {
    id: 45,
    title: "Educação Física",
    category: "Bacharelado",
    categorySlug: "graduacao",
    duration: "4 anos",
    price: "R$ 547,00",
    originalPrice: "R$ 747,00",
    image: "/placeholder.svg",
  },
  {
    id: 46,
    title: "Engenharia de Aplicação",
    category: "Bacharelado",
    categorySlug: "graduacao",
    duration: "4 anos",
    price: "R$ 647,00",
    originalPrice: "R$ 847,00",
    image: "/placeholder.svg",
  },
  {
    id: 47,
    title: "Engenharia de Dados",
    category: "Bacharelado",
    categorySlug: "graduacao",
    duration: "4 anos",
    price: "R$ 647,00",
    originalPrice: "R$ 847,00",
    image: "/placeholder.svg",
  },
  {
    id: 48,
    title: "Engenharia de Design Digital",
    category: "Bacharelado",
    categorySlug: "graduacao",
    duration: "4 anos",
    price: "R$ 647,00",
    originalPrice: "R$ 847,00",
    image: "/placeholder.svg",
  },
  {
    id: 49,
    title: "Engenharia de Manutenção e Diagnóstico Industrial",
    category: "Bacharelado",
    categorySlug: "graduacao",
    duration: "4 anos",
    price: "R$ 647,00",
    originalPrice: "R$ 847,00",
    image: "/placeholder.svg",
  },
  {
    id: 50,
    title: "Engenharia de Sistemas",
    category: "Bacharelado",
    categorySlug: "graduacao",
    duration: "4 anos",
    price: "R$ 647,00",
    originalPrice: "R$ 847,00",
    image: "/placeholder.svg",
  },
  {
    id: 51,
    title: "Engenharia de Software",
    category: "Bacharelado",
    categorySlug: "graduacao",
    duration: "4 anos",
    price: "R$ 647,00",
    originalPrice: "R$ 847,00",
    image: "/placeholder.svg",
  },
  {
    id: 52,
    title: "Psicopedagogia",
    category: "Bacharelado",
    categorySlug: "graduacao",
    duration: "4 anos",
    price: "R$ 597,00",
    originalPrice: "R$ 797,00",
    image: "/placeholder.svg",
  },
  {
    id: 53,
    title: "Publicidade e Propaganda",
    category: "Bacharelado",
    categorySlug: "graduacao",
    duration: "4 anos",
    price: "R$ 597,00",
    originalPrice: "R$ 797,00",
    image: "/placeholder.svg",
  },
  {
    id: 54,
    title: "Relações Internacionais",
    category: "Bacharelado",
    categorySlug: "graduacao",
    duration: "4 anos",
    price: "R$ 597,00",
    originalPrice: "R$ 797,00",
    image: "/placeholder.svg",
  },
  {
    id: 55,
    title: "Serviço Social",
    category: "Bacharelado",
    categorySlug: "graduacao",
    duration: "4 anos",
    price: "R$ 547,00",
    originalPrice: "R$ 747,00",
    image: "/placeholder.svg",
  },
  {
    id: 56,
    title: "Artes Visuais",
    category: "Segunda Licenciatura",
    categorySlug: "segunda-graduacao",
    duration: "1 ano",
    price: "R$ 397,00",
    originalPrice: "R$ 597,00",
    image: "/placeholder.svg",
  },
  {
    id: 57,
    title: "Sociologia",
    category: "Segunda Licenciatura",
    categorySlug: "segunda-graduacao",
    duration: "1 ano",
    price: "R$ 397,00",
    originalPrice: "R$ 597,00",
    image: "/placeholder.svg",
  },
  {
    id: 58,
    title: "Ciências da Religião",
    category: "Segunda Licenciatura",
    categorySlug: "segunda-graduacao",
    duration: "1 ano",
    price: "R$ 397,00",
    originalPrice: "R$ 597,00",
    image: "/placeholder.svg",
  },
  {
    id: 59,
    title: "Educação Especial",
    category: "Segunda Licenciatura",
    categorySlug: "segunda-graduacao",
    duration: "1 ano",
    price: "R$ 397,00",
    originalPrice: "R$ 597,00",
    image: "/placeholder.svg",
  },
  {
    id: 60,
    title: "Educação Física",
    category: "Segunda Licenciatura",
    categorySlug: "segunda-graduacao",
    duration: "1 ano",
    price: "R$ 397,00",
    originalPrice: "R$ 597,00",
    image: "/placeholder.svg",
  },
  {
    id: 61,
    title: "Filosofia",
    category: "Segunda Licenciatura",
    categorySlug: "segunda-graduacao",
    duration: "1 ano",
    price: "R$ 397,00",
    originalPrice: "R$ 597,00",
    image: "/placeholder.svg",
  },
  {
    id: 62,
    title: "Geografia",
    category: "Segunda Licenciatura",
    categorySlug: "segunda-graduacao",
    duration: "1 ano",
    price: "R$ 397,00",
    originalPrice: "R$ 597,00",
    image: "/placeholder.svg",
  },
  {
    id: 63,
    title: "História",
    category: "Segunda Licenciatura",
    categorySlug: "segunda-graduacao",
    duration: "1 ano",
    price: "R$ 397,00",
    originalPrice: "R$ 597,00",
    image: "/placeholder.svg",
  },
  {
    id: 64,
    title: "Letras - Língua Portuguesa e Libras",
    category: "Segunda Licenciatura",
    categorySlug: "segunda-graduacao",
    duration: "1 ano",
    price: "R$ 397,00",
    originalPrice: "R$ 597,00",
    image: "/placeholder.svg",
  },
  {
    id: 65,
    title: "Matemática",
    category: "Segunda Licenciatura",
    categorySlug: "segunda-graduacao",
    duration: "1 ano",
    price: "R$ 397,00",
    originalPrice: "R$ 597,00",
    image: "/placeholder.svg",
  },
  {
    id: 66,
    title: "Música",
    category: "Segunda Licenciatura",
    categorySlug: "segunda-graduacao",
    duration: "1 ano",
    price: "R$ 397,00",
    originalPrice: "R$ 597,00",
    image: "/placeholder.svg",
  },
  {
    id: 67,
    title: "Letras Português/Inglês",
    category: "Segunda Licenciatura",
    categorySlug: "segunda-graduacao",
    duration: "1 ano",
    price: "R$ 397,00",
    originalPrice: "R$ 597,00",
    image: "/placeholder.svg",
  },
  {
    id: 68,
    title: "Letras Português/Espanhol",
    category: "Segunda Licenciatura",
    categorySlug: "segunda-graduacao",
    duration: "1 ano",
    price: "R$ 397,00",
    originalPrice: "R$ 597,00",
    image: "/placeholder.svg",
  },
  
  // Novos cursos de Segunda Graduação Bacharelado
  {
    id: 82,
    title: "Administração - 12 meses",
    category: "Segunda Graduação Bacharelado",
    categorySlug: "segunda-graduacao-bacharelado",
    duration: "12 meses",
    price: "R$ 497,00",
    originalPrice: "R$ 697,00",
    image: "/lovable-uploads/4fb9144a-86ed-4030-8d66-cdb558e4703b.png",
  },
  {
    id: 83,
    title: "Psicopedagogia",
    category: "Segunda Graduação Bacharelado",
    categorySlug: "segunda-graduacao-bacharelado",
    duration: "12 meses",
    price: "R$ 497,00",
    originalPrice: "R$ 697,00",
    image: "/lovable-uploads/4fb9144a-86ed-4030-8d66-cdb558e4703b.png",
  },
  {
    id: 84,
    title: "Educação Física",
    category: "Segunda Graduação Bacharelado",
    categorySlug: "segunda-graduacao-bacharelado",
    duration: "12 meses",
    price: "R$ 497,00",
    originalPrice: "R$ 697,00",
    image: "/lovable-uploads/4fb9144a-86ed-4030-8d66-cdb558e4703b.png",
  },
  {
    id: 85,
    title: "Administração - 18 meses",
    category: "Segunda Graduação Bacharelado",
    categorySlug: "segunda-graduacao-bacharelado",
    duration: "18 meses",
    price: "R$ 497,00",
    originalPrice: "R$ 697,00",
    image: "/lovable-uploads/4fb9144a-86ed-4030-8d66-cdb558e4703b.png",
  },
  {
    id: 86,
    title: "Ciências Contábeis - 12 meses",
    category: "Segunda Graduação Bacharelado",
    categorySlug: "segunda-graduacao-bacharelado",
    duration: "12 meses",
    price: "R$ 497,00",
    originalPrice: "R$ 697,00",
    image: "/lovable-uploads/4fb9144a-86ed-4030-8d66-cdb558e4703b.png",
  },
  {
    id: 87,
    title: "Ciências Contábeis - 18 meses",
    category: "Segunda Graduação Bacharelado",
    categorySlug: "segunda-graduacao-bacharelado",
    duration: "18 meses",
    price: "R$ 497,00",
    originalPrice: "R$ 697,00",
    image: "/lovable-uploads/4fb9144a-86ed-4030-8d66-cdb558e4703b.png",
  },
  {
    id: 88,
    title: "Serviço Social",
    category: "Segunda Graduação Bacharelado",
    categorySlug: "segunda-graduacao-bacharelado",
    duration: "12 meses",
    price: "R$ 497,00",
    originalPrice: "R$ 697,00",
    image: "/lovable-uploads/4fb9144a-86ed-4030-8d66-cdb558e4703b.png",
  },
  
  // Cursos de Pós-Graduação na área de Educação
  {
    id: 101,
    title: "Alfabetização e Letramento",
    category: "Pós-Graduação",
    categorySlug: "pos-graduacao",
    duration: "12 meses",
    price: "R$ 397,00",
    originalPrice: "R$ 597,00",
    image: "/placeholder.svg",
  },
  {
    id: 102,
    title: "Alfabetização e Letramento e a Psicopedagogia",
    category: "Pós-Graduação",
    categorySlug: "pos-graduacao",
    duration: "12 meses",
    price: "R$ 397,00",
    originalPrice: "R$ 597,00",
    image: "/placeholder.svg",
  },
  {
    id: 103,
    title: "Arteterapia",
    category: "Pós-Graduação",
    categorySlug: "pos-graduacao",
    duration: "12 meses",
    price: "R$ 397,00",
    originalPrice: "R$ 597,00",
    image: "/placeholder.svg",
  },
  {
    id: 104,
    title: "Atendimento Educacional Especializado com Ênfase em Educação Especial e Inclusiva",
    category: "Pós-Graduação",
    categorySlug: "pos-graduacao",
    duration: "12 meses",
    price: "R$ 397,00",
    originalPrice: "R$ 597,00",
    image: "/placeholder.svg",
  },
  {
    id: 105,
    title: "Biblioteconomia",
    category: "Pós-Graduação",
    categorySlug: "pos-graduacao",
    duration: "12 meses",
    price: "R$ 397,00",
    originalPrice: "R$ 597,00",
    image: "/placeholder.svg",
  },
  {
    id: 106,
    title: "Coordenação e Orientação Escolar",
    category: "Pós-Graduação",
    categorySlug: "pos-graduacao",
    duration: "12 meses",
    price: "R$ 397,00",
    originalPrice: "R$ 597,00",
    image: "/placeholder.svg",
  },
  {
    id: 107,
    title: "Coordenação Educacional",
    category: "Pós-Graduação",
    categorySlug: "pos-graduacao",
    duration: "12 meses",
    price: "R$ 397,00",
    originalPrice: "R$ 597,00",
    image: "/placeholder.svg",
  },
  {
    id: 108,
    title: "Educação 5.0",
    category: "Pós-Graduação",
    categorySlug: "pos-graduacao",
    duration: "12 meses",
    price: "R$ 397,00",
    originalPrice: "R$ 597,00",
    image: "/placeholder.svg",
  },
  {
    id: 109,
    title: "Educação Ambiental e Sustentabilidade",
    category: "Pós-Graduação",
    categorySlug: "pos-graduacao",
    duration: "12 meses",
    price: "R$ 397,00",
    originalPrice: "R$ 597,00",
    image: "/placeholder.svg",
  },
  {
    id: 110,
    title: "Educação de Jovens e Adultos",
    category: "Pós-Graduação",
    categorySlug: "pos-graduacao",
    duration: "12 meses",
    price: "R$ 397,00",
    originalPrice: "R$ 597,00",
    image: "/placeholder.svg",
  },
  {
    id: 111,
    title: "Educação e Direitos Humanos",
    category: "Pós-Graduação",
    categorySlug: "pos-graduacao",
    duration: "12 meses",
    price: "R$ 397,00",
    originalPrice: "R$ 597,00",
    image: "/placeholder.svg",
  },
  {
    id: 112,
    title: "Educação Especial e Inclusiva",
    category: "Pós-Graduação",
    categorySlug: "pos-graduacao",
    duration: "12 meses",
    price: "R$ 397,00",
    originalPrice: "R$ 597,00",
    image: "/placeholder.svg",
  },
  {
    id: 113,
    title: "Educação Financeira",
    category: "Pós-Graduação",
    categorySlug: "pos-graduacao",
    duration: "12 meses",
    price: "R$ 397,00",
    originalPrice: "R$ 597,00",
    image: "/placeholder.svg",
  },
  {
    id: 114,
    title: "Educação Inclusiva e Diversidade",
    category: "Pós-Graduação",
    categorySlug: "pos-graduacao",
    duration: "12 meses",
    price: "R$ 397,00",
    originalPrice: "R$ 597,00",
    image: "/placeholder.svg",
  },
  {
    id: 115,
    title: "Educação Infantil",
    category: "Pós-Graduação",
    categorySlug: "pos-graduacao",
    duration: "12 meses",
    price: "R$ 397,00",
    originalPrice: "R$ 597,00",
    image: "/placeholder.svg",
  },
  {
    id: 116,
    title: "Educação Musical",
    category: "Pós-Graduação",
    categorySlug: "pos-graduacao",
    duration: "12 meses",
    price: "R$ 397,00",
    originalPrice: "R$ 597,00",
    image: "/placeholder.svg",
  },
  {
    id: 117,
    title: "Ensino da Língua Espanhola",
    category: "Pós-Graduação",
    categorySlug: "pos-graduacao",
    duration: "12 meses",
    price: "R$ 397,00",
    originalPrice: "R$ 597,00",
    image: "/placeholder.svg",
  },
  {
    id: 118,
    title: "Ensino da Língua Inglesa",
    category: "Pós-Graduação",
    categorySlug: "pos-graduacao",
    duration: "12 meses",
    price: "R$ 397,00",
    originalPrice: "R$ 597,00",
    image: "/placeholder.svg",
  },
  {
    id: 119,
    title: "Ensino da Língua Português",
    category: "Pós-Graduação",
    categorySlug: "pos-graduacao",
    duration: "12 meses",
    price: "R$ 397,00",
    originalPrice: "R$ 597,00",
    image: "/placeholder.svg",
  },
  {
    id: 120,
    title: "Ensino de Literatura e Produção de Textos em Língua Espanhola",
    category: "Pós-Graduação",
    categorySlug: "pos-graduacao",
    duration: "12 meses",
    price: "R$ 397,00",
    originalPrice: "R$ 597,00",
    image: "/placeholder.svg",
  },
  {
    id: 121,
    title: "Ensino de Literatura e Produção de Textos em Língua Inglesa",
    category: "Pós-Graduação",
    categorySlug: "pos-graduacao",
    duration: "12 meses",
    price: "R$ 397,00",
    originalPrice: "R$ 597,00",
    image: "/placeholder.svg",
  },
  {
    id: 122,
    title: "Ensino de Literatura e Produção de Textos em Língua Portuguesa",
    category: "Pós-Graduação",
    categorySlug: "pos-graduacao",
    duration: "12 meses",
    price: "R$ 397,00",
    originalPrice: "R$ 597,00",
    image: "/placeholder.svg",
  },
  {
    id: 123,
    title: "Ensino de Artes",
    category: "Pós-Graduação",
    categorySlug: "pos-graduacao",
    duration: "12 meses",
    price: "R$ 397,00",
    originalPrice: "R$ 597,00",
    image: "/placeholder.svg",
  },
  {
    id: 124,
    title: "Ensino de Ciências",
    category: "Pós-Graduação",
    categorySlug: "pos-graduacao",
    duration: "12 meses",
    price: "R$ 397,00",
    originalPrice: "R$ 597,00",
    image: "/placeholder.svg",
  },
  {
    id: 125,
    title: "Ensino de Geografia",
    category: "Pós-Graduação",
    categorySlug: "pos-graduacao",
    duration: "12 meses",
    price: "R$ 397,00",
    originalPrice: "R$ 597,00",
    image: "/placeholder.svg",
  },
  {
    id: 126,
    title: "Ensino de História",
    category: "Pós-Graduação",
    categorySlug: "pos-graduacao",
    duration: "12 meses",
    price: "R$ 397,00",
    originalPrice: "R$ 597,00",
    image: "/placeholder.svg",
  },
  {
    id: 127,
    title: "Ensino de História e Geografia",
    category: "Pós-Graduação",
    categorySlug: "pos-graduacao",
    duration: "12 meses",
    price: "R$ 397,00",
    originalPrice: "R$ 597,00",
    image: "/placeholder.svg",
  },
  {
    id: 128,
    title: "Ensino de Matemática",
    category: "Pós-Graduação",
    categorySlug: "pos-graduacao",
    duration: "12 meses",
    price: "R$ 397,00",
    originalPrice: "R$ 597,00",
    image: "/placeholder.svg",
  },
  {
    id: 129,
    title: "Ensino Religioso",
    category: "Pós-Graduação",
    categorySlug: "pos-graduacao",
    duration: "12 meses",
    price: "R$ 397,00",
    originalPrice: "R$ 597,00",
    image: "/placeholder.svg",
  },
  {
    id: 130,
    title: "Gestão e Orientação Escolar",
    category: "Pós-Graduação",
    categorySlug: "pos-graduacao",
    duration: "12 meses",
    price: "R$ 397,00",
    originalPrice: "R$ 597,00",
    image: "/placeholder.svg",
  },
  {
    id: 131,
    title: "Gestão Educacional",
    category: "Pós-Graduação",
    categorySlug: "pos-graduacao",
    duration: "12 meses",
    price: "R$ 397,00",
    originalPrice: "R$ 597,00",
    image: "/placeholder.svg",
  },
  {
    id: 132,
    title: "Gestão Educacional Pública",
    category: "Pós-Graduação",
    categorySlug: "pos-graduacao",
    duration: "12 meses",
    price: "R$ 397,00",
    originalPrice: "R$ 597,00",
    image: "/placeholder.svg",
  },
  {
    id: 133,
    title: "Gestão Escolar Integradora com Ênfase em Supervisão, Orientação, Administração e Inspeção",
    category: "Pós-Graduação",
    categorySlug: "pos-graduacao",
    duration: "12 meses",
    price: "R$ 397,00",
    originalPrice: "R$ 597,00",
    image: "/placeholder.svg",
  },
  {
    id: 134,
    title: "História da Arte",
    category: "Pós-Graduação",
    categorySlug: "pos-graduacao",
    duration: "12 meses",
    price: "R$ 397,00",
    originalPrice: "R$ 597,00",
    image: "/placeholder.svg",
  },
  {
    id: 135,
    title: "História e Fundamentos da Filosofia",
    category: "Pós-Graduação",
    categorySlug: "pos-graduacao",
    duration: "12 meses",
    price: "R$ 397,00",
    originalPrice: "R$ 597,00",
    image: "/placeholder.svg",
  },
  {
    id: 136,
    title: "Inspeção Escolar",
    category: "Pós-Graduação",
    categorySlug: "pos-graduacao",
    duration: "12 meses",
    price: "R$ 397,00",
    originalPrice: "R$ 597,00",
    image: "/placeholder.svg",
  },
  {
    id: 137,
    title: "Letramento e Produção de Texto para o Ensino Médio",
    category: "Pós-Graduação",
    categorySlug: "pos-graduacao",
    duration: "12 meses",
    price: "R$ 397,00",
    originalPrice: "R$ 597,00",
    image: "/placeholder.svg",
  },
  {
    id: 138,
    title: "Letras com Ênfase em Linguística",
    category: "Pós-Graduação",
    categorySlug: "pos-graduacao",
    duration: "12 meses",
    price: "R$ 397,00",
    originalPrice: "R$ 597,00",
    image: "/placeholder.svg",
  },
  {
    id: 139,
    title: "Libras",
    category: "Pós-Graduação",
    categorySlug: "pos-graduacao",
    duration: "12 meses",
    price: "R$ 397,00",
    originalPrice: "R$ 597,00",
    image: "/placeholder.svg",
  },
  {
    id: 140,
    title: "Língua Portuguesa, Redação e Oratória",
    category: "Pós-Graduação",
    categorySlug: "pos-graduacao",
    duration: "12 meses",
    price: "R$ 397,00",
    originalPrice: "R$ 597,00",
    image: "/placeholder.svg",
  },
  {
    id: 141,
    title: "Metodologia do Ensino da Matemática",
    category: "Pós-Graduação",
    categorySlug: "pos-graduacao",
    duration: "12 meses",
    price: "R$ 397,00",
    originalPrice: "R$ 597,00",
    image: "/placeholder.svg",
  },
  {
    id: 142,
    title: "Metodologia do Ensino de Matemática e Física",
    category: "Pós-Graduação",
    categorySlug: "pos-graduacao",
    duration: "12 meses",
    price: "R$ 397,00",
    originalPrice: "R$ 597,00",
    image: "/placeholder.svg",
  },
  {
    id: 143,
    title: "Metodologia do Ensino de Filosofia e Sociologia",
    category: "Pós-Graduação",
    categorySlug: "pos-graduacao",
    duration: "12 meses",
    price: "R$ 397,00",
    originalPrice: "R$ 597,00",
    image: "/placeholder.svg",
  },
  {
    id: 144,
    title: "Metodologia do Ensino de Filosofia",
    category: "Pós-Graduação",
    categorySlug: "pos-graduacao",
    duration: "12 meses",
    price: "R$ 397,00",
    originalPrice: "R$ 597,00",
    image: "/placeholder.svg",
  },
  {
    id: 145,
    title: "Metodologia do Ensino de Literatura Africana e Indígena",
    category: "Pós-Graduação",
    categorySlug: "pos-graduacao",
    duration: "12 meses",
    price: "R$ 397,00",
    originalPrice: "R$ 597,00",
    image: "/placeholder.svg",
  },
  {
    id: 146,
    title: "Metodologia do Ensino de Sociologia",
    category: "Pós-Graduação",
    categorySlug: "pos-graduacao",
    duration: "12 meses",
    price: "R$ 397,00",
    originalPrice: "R$ 597,00",
    image: "/placeholder.svg",
  },
  {
    id: 147,
    title: "Metodologia do Ensino Superior e as Várias Modalidades",
    category: "Pós-Graduação",
    categorySlug: "pos-graduacao",
    duration: "12 meses",
    price: "R$ 397,00",
    originalPrice: "R$ 597,00",
    image: "/placeholder.svg",
  },
  {
    id: 148,
    title: "Metodologias Ativas e Tecnologias Educacionais",
    category: "Pós-Graduação",
    categorySlug: "pos-graduacao",
    duration: "12 meses",
    price: "R$ 397,00",
    originalPrice: "R$ 597,00",
    image: "/placeholder.svg",
  },
  {
    id: 149,
    title: "Musicoterapia",
    category: "Pós-Graduação",
    categorySlug: "pos-graduacao",
    duration: "12 meses",
    price: "R$ 397,00",
    originalPrice: "R$ 597,00",
    image: "/placeholder.svg",
  },
  {
    id: 150,
    title: "Neurociências e Aprendizagem",
    category: "Pós-Graduação",
    categorySlug: "pos-graduacao",
    duration: "12 meses",
    price: "R$ 397,00",
    originalPrice: "R$ 597,00",
    image: "/placeholder.svg",
  },
  {
    id: 151,
    title: "Neuroeducação",
    category: "Pós-Graduação",
    categorySlug: "pos-graduacao",
    duration: "12 meses",
    price: "R$ 397,00",
    originalPrice: "R$ 597,00",
    image: "/placeholder.svg",
  },
  {
    id: 152,
    title: "Neuropsicologia Clínica",
    category: "Pós-Graduação",
    categorySlug: "pos-graduacao",
    duration: "12 meses",
    price: "R$ 397,00",
    originalPrice: "R$ 597,00",
    image: "/placeholder.svg",
  },
  {
    id: 153,
    title: "Neuropsicologia",
    category: "Pós-Graduação",
    categorySlug: "pos-graduacao",
    duration: "12 meses",
    price: "R$ 397,00",
    originalPrice: "R$ 597,00",
    image: "/placeholder.svg",
  },
  {
    id: 154,
    title: "Neuropsicopedagogia Clínica e Institucional",
    category: "Pós-Graduação",
    categorySlug: "pos-graduacao",
    duration: "12 meses",
    price: "R$ 397,00",
    originalPrice: "R$ 597,00",
    image: "/placeholder.svg",
  },
  {
    id: 155,
    title: "Neuropsicopedagogia Clínica",
    category: "Pós-Graduação",
    categorySlug: "pos-graduacao",
    duration: "12 meses",
    price: "R$ 397,00",
    originalPrice: "R$ 597,00",
    image: "/placeholder.svg",
  },
  {
    id: 156,
    title: "Orientação Educacional",
    category: "Pós-Graduação",
    categorySlug: "pos-graduacao",
    duration: "12 meses",
    price: "R$ 397,00",
    originalPrice: "R$ 597,00",
    image: "/placeholder.svg",
  },
  {
    id: 157,
    title: "Orientação Escolar",
    category: "Pós-Graduação",
    categorySlug: "pos-graduacao",
    duration: "12 meses",
    price: "R$ 397,00",
    originalPrice: "R$ 597,00",
    image: "/placeholder.svg",
  },
  {
    id: 158,
    title: "Projetos Pedagógicos",
    category: "Pós-Graduação",
    categorySlug: "pos-graduacao",
    duration: "12 meses",
    price: "R$ 397,00",
    originalPrice: "R$ 597,00",
    image: "/placeholder.svg",
  },
  {
    id: 159,
    title: "Psicomotricidade",
    category: "Pós-Graduação",
    categorySlug: "pos-graduacao",
    duration: "12 meses",
    price: "R$ 397,00",
    originalPrice: "R$ 597,00",
    image: "/placeholder.svg",
  },
  {
    id: 160,
    title: "Psicomotricidade e Educação Especial",
    category: "Pós-Graduação",
    categorySlug: "pos-graduacao",
    duration: "12 meses",
    price: "R$ 397,00",
    originalPrice: "R$ 597,00",
    image: "/placeholder.svg",
  },
  {
    id: 161,
    title: "Psicomotricidade na Educação Infantil",
    category: "Pós-Graduação",
    categorySlug: "pos-graduacao",
    duration: "12 meses",
    price: "R$ 397,00",
    originalPrice: "R$ 597,00",
    image: "/placeholder.svg",
  },
  {
    id: 162,
    title: "Psicopedagogia em Educação Especial",
    category: "Pós-Graduação",
    categorySlug: "pos-graduacao",
    duration: "12 meses",
    price: "R$ 397,00",
    originalPrice: "R$ 597,00",
    image: "/placeholder.svg",
  },
  {
    id: 163,
    title: "Psicopedagogia Escolar",
    category: "Pós-Graduação",
    categorySlug: "pos-graduacao",
    duration: "12 meses",
    price: "R$ 397,00",
    originalPrice: "R$ 597,00",
    image: "/placeholder.svg",
  },
  {
    id: 164,
    title: "Secretariado Escolar",
    category: "Pós-Graduação",
    categorySlug: "pos-graduacao",
    duration: "12 meses",
    price: "R$ 397,00",
    originalPrice: "R$ 597,00",
    image: "/placeholder.svg",
  },
  {
    id: 165,
    title: "Sexologia",
    category: "Pós-Graduação",
    categorySlug: "pos-graduacao",
    duration: "12 meses",
    price: "R$ 397,00",
    originalPrice: "R$ 597,00",
    image: "/placeholder.svg",
  },
  {
    id: 166,
    title: "Supervisão e Orientação em Educação Infantil",
    category: "Pós-Graduação",
    categorySlug: "pos-graduacao",
    duration: "12 meses",
    price: "R$ 397,00",
    originalPrice: "R$ 597,00",
    image: "/placeholder.svg",
  },
  {
    id: 167,
    title: "Supervisão Escolar",
    category: "Pós-Graduação",
    categorySlug: "pos-graduacao",
    duration: "12 meses",
    price: "R$ 397,00",
    originalPrice: "R$ 597,00",
    image: "/placeholder.svg",
  },
  {
    id: 168,
    title: "Supervisão e Orientação Escolar",
    category: "Pós-Graduação",
    categorySlug: "pos-graduacao",
    duration: "12 meses",
    price: "R$ 397,00",
    originalPrice: "R$ 597,00",
    image: "/placeholder.svg",
  },
  {
    id: 169,
    title: "TDAH - Transtorno do Déficit de Atenção e Hiperatividade",
    category: "Pós-Graduação",
    categorySlug: "pos-graduacao",
    duration: "12 meses",
    price: "R$ 397,00",
    originalPrice: "R$ 597,00",
    image: "/placeholder.svg",
  },
  {
    id: 170,
    title: "Tecnologias Educacionais",
    category: "Pós-Graduação",
    categorySlug: "pos-graduacao",
    duration: "12 meses",
    price: "R$ 397,00",
    originalPrice: "R$ 597,00",
    image: "/placeholder.svg",
  },
  {
    id: 171,
    title: "Terapia em TDAH Clínica",
    category: "Pós-Graduação",
    categorySlug: "pos-graduacao",
    duration: "12 meses",
    price: "R$ 397,00",
    originalPrice: "R$ 597,00",
    image: "/placeholder.svg",
  },
  {
    id: 172,
    title: "Terapia em ABA: Análise do Comportamento Aplicada",
    category: "Pós-Graduação",
    categorySlug: "pos-graduacao",
    duration: "12 meses",
    price: "R$ 397,00",
    originalPrice: "R$ 597,00",
    image: "/placeholder.svg",
  },
  {
    id: 173,
    title: "Terapia em ABA: Análise do Comportamento Aplicada Clínico",
    category: "Pós-Graduação",
    categorySlug: "pos-graduacao",
    duration: "12 meses",
    price: "R$ 397,00",
    originalPrice: "R$ 597,00",
    image: "/placeholder.svg",
  },
  {
    id: 174,
    title: "Transtornos e Problemas na Aprendizagem",
    category: "Pós-Graduação",
    categorySlug: "pos-graduacao",
    duration: "12 meses",
    price: "R$ 397,00",
    originalPrice: "R$ 597,00",
    image: "/placeholder.svg",
  },
  {
    id: 175,
    title: "Tutoria em Educação a Distância",
    category: "Pós-Graduação",
    categorySlug: "pos-graduacao",
    duration: "12 meses",
    price: "R$ 397,00",
    originalPrice: "R$ 597,00",
    image: "/placeholder.svg",
  },
];

const Cursos = () => {
  const { categoria } = useParams();
  const [currentCategory, setCurrentCategory] = useState(categoria || "todos");
  const [searchTerm, setSearchTerm] = useState("");
  
  useEffect(() => {
    if (categoria) {
      setCurrentCategory(categoria);
    }
  }, [categoria]);
  
  // Filtrar cursos com base na categoria selecionada e termo de busca
  const filteredCourses = mockCourses
    .filter(course => currentCategory === "todos" || course.categorySlug === currentCategory)
    .filter(course => 
      searchTerm === "" || 
      course.title.toLowerCase().includes(searchTerm.toLowerCase()) ||
      course.category.toLowerCase().includes(searchTerm.toLowerCase())
    );

  // Categorias disponíveis - Adicionando a nova categoria Segunda Graduação Bacharelado
  const categories = [
    { id: "todos", name: "Todos os Cursos" },
    { id: "graduacao", name: "Graduação" },
    { id: "segunda-graduacao", name: "Segunda Graduação" },
    { id: "segunda-graduacao-bacharelado", name: "Segunda Graduação Bacharelado" },
    { id: "pos-graduacao", name: "Pós-Graduação" },
    { id: "formacao-livre", name: "Formação Livre" },
    { id: "capacitacao-profissional", name: "Capacitação Profissional" },
    { id: "formacao-pedagogica", name: "Formação Pedagógica" }
  ];

  return (
    <MainLayout>
      <div className="bg-gray-50 py-8">
        <div className="eduzayn-container">
          <h1 className="text-3xl font-bold mb-6">
            {currentCategory === "todos" 
              ? "Todos os Cursos" 
              : categories.find(cat => cat.id === currentCategory)?.name || "Cursos"}
          </h1>
          
          {/* Campo de Busca */}
          <div className="relative mb-6">
            <div className="relative">
              <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400" />
              <Input 
                type="text"
                placeholder="Buscar por nome de curso ou categoria..."
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                className="pl-10 w-full"
              />
            </div>
          </div>
          
          {/* Filtros de Categoria */}
          <div className="mb-8 overflow-x-auto pb-2">
            <div className="flex space-x-2">
              {categories.map((cat) => (
                <Button 
                  key={cat.id} 
                  variant={currentCategory === cat.id ? "default" : "outline"}
                  className="whitespace-nowrap"
                  onClick={() => setCurrentCategory(cat.id)}
                >
                  {cat.name}
                </Button>
              ))}
            </div>
          </div>
          
          {/* Resultados da busca */}
          {searchTerm && (
            <p className="mb-4 text-gray-600">
              Exibindo {filteredCourses.length} resultado(s) para "{searchTerm}"
            </p>
          )}
          
          {/* Grid de Cursos */}
          {filteredCourses.length === 0 ? (
            <div className="text-center py-12">
              <h3 className="text-xl font-medium text-gray-700 mb-2">Nenhum curso encontrado</h3>
              <p className="text-gray-500">Tente modificar sua busca ou filtros.</p>
            </div>
          ) : (
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
              {filteredCourses.map((course) => (
                <Card key={course.id} className="overflow-hidden">
                  <div className="relative h-48 overflow-hidden">
                    <img 
                      src={course.image} 
                      alt={course.title}
                      className="w-full h-full object-cover hover:scale-105 transition-transform duration-300"
                    />
                    <div className="absolute top-3 right-3">
                      <Badge className="bg-primary">{course.category}</Badge>
                    </div>
                  </div>
                  
                  <CardHeader className="pb-2">
                    <CardTitle className="text-xl">
                      <Link to={`/curso/${course.id}`} className="hover:text-primary transition-colors">
                        {course.title}
                      </Link>
                    </CardTitle>
                  </CardHeader>
                  
                  <CardContent className="pb-2 space-y-3">
                    <div className="flex items-center space-x-4 text-sm text-gray-600">
                      <div className="flex items-center">
                        <Clock className="h-4 w-4 mr-1" />
                        <span>{course.duration}</span>
                      </div>
                      <div className="flex items-center">
                        <Award className="h-4 w-4 mr-1" />
                        <span>Certificado</span>
                      </div>
                    </div>
                    
                    <div className="flex items-end gap-2">
                      <span className="text-xl font-bold text-primary">{course.price}</span>
                      <span className="text-sm text-gray-500 line-through">{course.originalPrice}</span>
                    </div>
                  </CardContent>
                  
                  <CardFooter>
                    <Button asChild className="w-full">
                      <Link to={`/curso/${course.id}`}>
                        Saiba Mais
                      </Link>
                    </Button>
                  </CardFooter>
                </Card>
              ))}
            </div>
          )}
        </div>
      </div>
    </MainLayout>
  );
};

export default Cursos;
