import React, { useState, useEffect } from "react";
import { useParams } from "react-router-dom";
import MainLayout from "@/components/layout/MainLayout";
import { Card, CardContent, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Link } from "react-router-dom";
import { Clock, Award, Search } from "lucide-react";
import { Input } from "@/components/ui/input";

// Dados simulados para os cursos
const mockCourses = [
  // Cursos existentes
  {
    id: 1,
    title: "Administração de Empresas",
    category: "Graduação",
    categorySlug: "graduacao",
    duration: "4 anos",
    price: "R$ 597,00",
    originalPrice: "R$ 897,00",
    image: "/placeholder.svg",
  },
  {
    id: 2,
    title: "Pedagogia",
    category: "Graduação",
    categorySlug: "graduacao",
    duration: "4 anos",
    price: "R$ 547,00",
    originalPrice: "R$ 847,00",
    image: "/placeholder.svg",
  },
  {
    id: 3,
    title: "Engenharia Civil",
    category: "Segunda Graduação",
    categorySlug: "segunda-graduacao",
    duration: "3 anos",
    price: "R$ 697,00",
    originalPrice: "R$ 997,00",
    image: "/placeholder.svg",
  },
  {
    id: 4,
    title: "Gestão de Recursos Humanos",
    category: "Pós-Graduação",
    categorySlug: "pos-graduacao",
    duration: "1.5 anos",
    price: "R$ 397,00",
    originalPrice: "R$ 597,00",
    image: "/placeholder.svg",
  },
  {
    id: 5,
    title: "Marketing Digital",
    category: "Pós-Graduação",
    categorySlug: "pos-graduacao",
    duration: "1.5 anos",
    price: "R$ 427,00",
    originalPrice: "R$ 627,00",
    image: "/placeholder.svg",
  },
  {
    id: 6,
    title: "Excel Avançado",
    category: "Formação Livre",
    categorySlug: "formacao-livre",
    duration: "60 horas",
    price: "R$ 197,00",
    originalPrice: "R$ 297,00",
    image: "/placeholder.svg",
  },
  {
    id: 7,
    title: "Técnicas de Vendas",
    category: "Capacitação Profissional",
    categorySlug: "capacitacao-profissional",
    duration: "80 horas",
    price: "R$ 247,00",
    originalPrice: "R$ 347,00",
    image: "/placeholder.svg",
  },
  {
    id: 8,
    title: "Data Science",
    category: "Capacitação Profissional",
    categorySlug: "capacitacao-profissional",
    duration: "120 horas",
    price: "R$ 347,00",
    originalPrice: "R$ 447,00",
    image: "/placeholder.svg",
  },
  
  // Novos cursos de graduação tecnológica (18 meses)
  {
    id: 9,
    title: "Análise e Desenvolvimento de Sistemas",
    category: "Graduação Tecnológica",
    categorySlug: "graduacao",
    duration: "18 meses",
    price: "R$ 497,00",
    originalPrice: "R$ 697,00",
    image: "/placeholder.svg",
  },
  {
    id: 10,
    title: "Big Data e Inteligência Analítica",
    category: "Graduação Tecnológica",
    categorySlug: "graduacao",
    duration: "18 meses",
    price: "R$ 497,00",
    originalPrice: "R$ 697,00",
    image: "/placeholder.svg",
  },
  {
    id: 11,
    title: "Cidades Inteligentes",
    category: "Graduação Tecnológica",
    categorySlug: "graduacao",
    duration: "18 meses",
    price: "R$ 497,00",
    originalPrice: "R$ 697,00",
    image: "/placeholder.svg",
  },
  {
    id: 12,
    title: "Coaching e Desenvolvimento Humano",
    category: "Graduação Tecnológica",
    categorySlug: "graduacao",
    duration: "18 meses",
    price: "R$ 497,00",
    originalPrice: "R$ 697,00",
    image: "/placeholder.svg",
  },
  {
    id: 13,
    title: "Comércio Exterior",
    category: "Graduação Tecnológica",
    categorySlug: "graduacao",
    duration: "18 meses",
    price: "R$ 497,00",
    originalPrice: "R$ 697,00",
    image: "/placeholder.svg",
  },
  {
    id: 14,
    title: "Design de Animação",
    category: "Graduação Tecnológica",
    categorySlug: "graduacao",
    duration: "18 meses",
    price: "R$ 497,00",
    originalPrice: "R$ 697,00",
    image: "/placeholder.svg",
  },
  {
    id: 15,
    title: "Designer de Interiores",
    category: "Graduação Tecnológica",
    categorySlug: "graduacao",
    duration: "18 meses",
    price: "R$ 497,00",
    originalPrice: "R$ 697,00",
    image: "/placeholder.svg",
  },
  {
    id: 16,
    title: "Designer de Produto",
    category: "Graduação Tecnológica",
    categorySlug: "graduacao",
    duration: "18 meses",
    price: "R$ 497,00",
    originalPrice: "R$ 697,00",
    image: "/placeholder.svg",
  },
  {
    id: 17,
    title: "Designer Gráfico",
    category: "Graduação Tecnológica",
    categorySlug: "graduacao",
    duration: "18 meses",
    price: "R$ 497,00",
    originalPrice: "R$ 697,00",
    image: "/placeholder.svg",
  },
  {
    id: 18,
    title: "Despachante Documentalista",
    category: "Graduação Tecnológica",
    categorySlug: "graduacao",
    duration: "18 meses",
    price: "R$ 497,00",
    originalPrice: "R$ 697,00",
    image: "/placeholder.svg",
  },
  {
    id: 19,
    title: "Educador Social",
    category: "Graduação Tecnológica",
    categorySlug: "graduacao",
    duration: "18 meses",
    price: "R$ 497,00",
    originalPrice: "R$ 697,00",
    image: "/placeholder.svg",
  },
  {
    id: 20,
    title: "Empreendedorismo Educacional",
    category: "Graduação Tecnológica",
    categorySlug: "graduacao",
    duration: "18 meses",
    price: "R$ 497,00",
    originalPrice: "R$ 697,00",
    image: "/placeholder.svg",
  },
  {
    id: 21,
    title: "Estética e Cosmética",
    category: "Graduação Tecnológica",
    categorySlug: "graduacao",
    duration: "18 meses",
    price: "R$ 497,00",
    originalPrice: "R$ 697,00",
    image: "/placeholder.svg",
  },
  {
    id: 22,
    title: "Gestão Ambiental",
    category: "Graduação Tecnológica",
    categorySlug: "graduacao",
    duration: "18 meses",
    price: "R$ 497,00",
    originalPrice: "R$ 697,00",
    image: "/placeholder.svg",
  },
  {
    id: 23,
    title: "Gestão Comercial",
    category: "Graduação Tecnológica",
    categorySlug: "graduacao",
    duration: "18 meses",
    price: "R$ 497,00",
    originalPrice: "R$ 697,00",
    image: "/placeholder.svg",
  },
  {
    id: 24,
    title: "Gestão da Produção Industrial",
    category: "Graduação Tecnológica",
    categorySlug: "graduacao",
    duration: "18 meses",
    price: "R$ 497,00",
    originalPrice: "R$ 697,00",
    image: "/placeholder.svg",
  },
  {
    id: 25,
    title: "Gestão da Qualidade",
    category: "Graduação Tecnológica",
    categorySlug: "graduacao",
    duration: "18 meses",
    price: "R$ 497,00",
    originalPrice: "R$ 697,00",
    image: "/placeholder.svg",
  },
  {
    id: 26,
    title: "Gestão de Agronegócios",
    category: "Graduação Tecnológica",
    categorySlug: "graduacao",
    duration: "18 meses",
    price: "R$ 497,00",
    originalPrice: "R$ 697,00",
    image: "/placeholder.svg",
  },
  {
    id: 27,
    title: "Gestão de Clínica e Consultório",
    category: "Graduação Tecnológica",
    categorySlug: "graduacao",
    duration: "18 meses",
    price: "R$ 497,00",
    originalPrice: "R$ 697,00",
    image: "/placeholder.svg",
  },
  {
    id: 28,
    title: "Gestão de Cooperativas",
    category: "Graduação Tecnológica",
    categorySlug: "graduacao",
    duration: "18 meses",
    price: "R$ 497,00",
    originalPrice: "R$ 697,00",
    image: "/placeholder.svg",
  },
  {
    id: 29,
    title: "Gestão de Investimentos",
    category: "Graduação Tecnológica",
    categorySlug: "graduacao",
    duration: "18 meses",
    price: "R$ 497,00",
    originalPrice: "R$ 697,00",
    image: "/placeholder.svg",
  },
  
  // Novos cursos de licenciatura (3.5+ anos)
  {
    id: 30,
    title: "Artes Visuais",
    category: "Licenciatura",
    categorySlug: "graduacao",
    duration: "3.5 anos",
    price: "R$ 497,00",
    originalPrice: "R$ 697,00",
    image: "/placeholder.svg",
  },
  {
    id: 31,
    title: "Ciências da Religião",
    category: "Licenciatura",
    categorySlug: "graduacao",
    duration: "3.5 anos",
    price: "R$ 497,00",
    originalPrice: "R$ 697,00",
    image: "/placeholder.svg",
  },
  {
    id: 32,
    title: "Educação Especial",
    category: "Licenciatura",
    categorySlug: "graduacao",
    duration: "3.5 anos",
    price: "R$ 497,00",
    originalPrice: "R$ 697,00",
    image: "/placeholder.svg",
  },
  {
    id: 33,
    title: "Educação Física",
    category: "Licenciatura",
    categorySlug: "graduacao",
    duration: "3.5 anos",
    price: "R$ 497,00",
    originalPrice: "R$ 697,00",
    image: "/placeholder.svg",
  },
  {
    id: 34,
    title: "Filosofia",
    category: "Licenciatura",
    categorySlug: "graduacao",
    duration: "3.5 anos",
    price: "R$ 497,00",
    originalPrice: "R$ 697,00",
    image: "/placeholder.svg",
  },
  {
    id: 35,
    title: "Geografia",
    category: "Licenciatura",
    categorySlug: "graduacao",
    duration: "3.5 anos",
    price: "R$ 497,00",
    originalPrice: "R$ 697,00",
    image: "/placeholder.svg",
  },
  {
    id: 36,
    title: "História",
    category: "Licenciatura",
    categorySlug: "graduacao",
    duration: "3.5 anos",
    price: "R$ 497,00",
    originalPrice: "R$ 697,00",
    image: "/placeholder.svg",
  },
  {
    id: 37,
    title: "Letras - Língua Portuguesa e Libras",
    category: "Licenciatura",
    categorySlug: "graduacao",
    duration: "3.5 anos",
    price: "R$ 497,00",
    originalPrice: "R$ 697,00",
    image: "/placeholder.svg",
  },
  {
    id: 38,
    title: "Letras - Português e Espanhol",
    category: "Licenciatura",
    categorySlug: "graduacao",
    duration: "3.5 anos",
    price: "R$ 497,00",
    originalPrice: "R$ 697,00",
    image: "/placeholder.svg",
  },
  {
    id: 39,
    title: "Letras - Português e Inglês",
    category: "Licenciatura",
    categorySlug: "graduacao",
    duration: "3.5 anos",
    price: "R$ 497,00",
    originalPrice: "R$ 697,00",
    image: "/placeholder.svg",
  },
  {
    id: 40,
    title: "Pedagogia",
    category: "Licenciatura",
    categorySlug: "graduacao",
    duration: "3.5 anos",
    price: "R$ 497,00",
    originalPrice: "R$ 697,00",
    image: "/placeholder.svg",
  },
  {
    id: 41,
    title: "Sociologia",
    category: "Licenciatura",
    categorySlug: "graduacao",
    duration: "3.5 anos",
    price: "R$ 497,00",
    originalPrice: "R$ 697,00",
    image: "/placeholder.svg",
  },
  
  // Novos cursos de Bacharelado (3.5+ anos)
  {
    id: 42,
    title: "Administração",
    category: "Bacharelado",
    categorySlug: "graduacao",
    duration: "4 anos",
    price: "R$ 547,00",
    originalPrice: "R$ 747,00",
    image: "/placeholder.svg",
  },
  {
    id: 43,
    title: "Biblioteconomia",
    category: "Bacharelado",
    categorySlug: "graduacao",
    duration: "4 anos",
    price: "R$ 547,00",
    originalPrice: "R$ 747,00",
    image: "/placeholder.svg",
  },
  {
    id: 44,
    title: "Ciências Contábeis",
    category: "Bacharelado",
    categorySlug: "graduacao",
    duration: "4 anos",
    price: "R$ 547,00",
    originalPrice: "R$ 747,00",
    image: "/placeholder.svg",
  },
  {
    id: 45,
    title: "Educação Física",
    category: "Bacharelado",
    categorySlug: "graduacao",
    duration: "4 anos",
    price: "R$ 547,00",
    originalPrice: "R$ 747,00",
    image: "/placeholder.svg",
  },
  {
    id: 46,
    title: "Engenharia de Aplicação",
    category: "Bacharelado",
    categorySlug: "graduacao",
    duration: "4 anos",
    price: "R$ 647,00",
    originalPrice: "R$ 847,00",
    image: "/placeholder.svg",
  },
  {
    id: 47,
    title: "Engenharia de Dados",
    category: "Bacharelado",
    categorySlug: "graduacao",
    duration: "4 anos",
    price: "R$ 647,00",
    originalPrice: "R$ 847,00",
    image: "/placeholder.svg",
  },
  {
    id: 48,
    title: "Engenharia de Design Digital",
    category: "Bacharelado",
    categorySlug: "graduacao",
    duration: "4 anos",
    price: "R$ 647,00",
    originalPrice: "R$ 847,
